from .propietarios import propietarios
from .cuentas import cuentas
from .apartamentos import apartamentos
from .torres import torres
from .pisos import pisos
from .ingresos import ingresos
from .recibos import recibos
from .egresos import egresos
from .facturas import facturas